name: Deploy to InfinityFree

on:
  push:
    branches:
      - main # Deploy on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: sebastianpopp/ftp-deploy-action@v1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Adjust this if your files are in a subdirectory
          remote-dir: /htdocs/ # Adjust this if you use a different directory on InfinityFree
